apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: adm
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://bitnami-labs.github.io/sealed-secrets
    name: sealed-secrets
    version: 2.7.3
